### ISSUE TITLE
train.py ends with an error

### ISSUE THREAD

**Issue by Thot-Htp** [nederhof/hocr#2]
When running:

`python train.py
`
The programs stop after several minutes with the error message:

```
Traceback (most recent call last):
  File "M:\Luca\Documents\Python\My_Programs\Hieroglyph OCR\hocr-main\src\train.py", line 392, in <module>
    train_letters_default()
  File "M:\Luca\Documents\Python\My_Programs\Hieroglyph OCR\hocr-main\src\train.py", line 381, in train_letters_default
    train_letters(font_dirs, model_dir, pca_dim)
  File "M:\Luca\Documents\Python\My_Programs\Hieroglyph OCR\hocr-main\src\train.py", line 330, in train_letters
    chars, styles, vecs, aspects, heights = get_prototypes_letters(prototype_dirs)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Luca\Documents\Python\My_Programs\Hieroglyph OCR\hocr-main\src\train.py", line 275, in get_prototypes_letters
    style, codepoints = filename.split(':')
    ^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```

Lines 274 and 275:

```
filename = re.sub('-[0-9]+', '', base)
style, codepoints = filename.split(':')
```

where the variable 'filename' which is causing the error: 'bold_100.png' 
`

Please advise

**Comment by nederhof** [comment]
There is no such file.
